BRAND_ALIASES={
"toyota":"toyota","тойота":"toyota",
"honda":"honda","хонда":"honda",
"nissan":"nissan","ніссан":"nissan",
"mazda":"mazda","мазда":"mazda",
"mitsubishi":"mitsubishi","міцубісі":"mitsubishi",
"subaru":"subaru","субару":"subaru",
"suzuki":"suzuki","сузукі":"suzuki",
"lexus":"lexus","лексус":"lexus",
"acura":"acura","акура":"acura",
"infiniti":"infiniti","інфініті":"infiniti",

"bmw":"bmw","бмв":"bmw",
"audi":"audi","ауді":"audi",
"mercedes":"mercedes-benz","мерседес":"mercedes-benz",
"mercedes-benz":"mercedes-benz","мерседес-бенц":"mercedes-benz",
"volkswagen":"volkswagen","фольксваген":"volkswagen",
"porsche":"porsche","порше":"porsche",
"opel":"opel","опель":"opel",
"skoda":"skoda","шкода":"skoda",
"seat":"seat","сеат":"seat",

"renault":"renault","рено":"renault",
"peugeot":"peugeot","пежо":"peugeot",
"citroen":"citroen","сітроен":"citroen",
"dacia":"dacia","дачія":"dacia",

"fiat":"fiat","фіат":"fiat",
"alfa romeo":"alfa romeo","альфа ромео":"alfa romeo",
"lamborghini":"lamborghini","ламборгіні":"lamborghini",
"ferrari":"ferrari","феррарі":"ferrari",
"maserati":"maserati","мазераті":"maserati",

"land rover":"land rover","ленд ровер":"land rover",
"jaguar":"jaguar","ягуар":"jaguar",
"aston martin":"aston martin","астон мартін":"aston martin",
"bentley":"bentley","бентлі":"bentley",
"rolls-royce":"rolls-royce","роллс-ройс":"rolls-royce",
"mini":"mini","міні":"mini",

"ford":"ford","форд":"ford",
"chevrolet":"chevrolet","шевроле":"chevrolet",
"dodge":"dodge","додж":"dodge",
"jeep":"jeep","джип":"jeep",
"cadillac":"cadillac","каділак":"cadillac",
"gmc":"gmc",
"ram":"ram","рам":"ram",
"tesla":"tesla","тесла":"tesla",
"lincoln":"lincoln","лінкольн":"lincoln",
"buick":"buick","бьюік":"buick",

"hyundai":"hyundai","хюндай":"hyundai",
"kia":"kia","кіа":"kia",
"ssangyong":"ssangyong","сангйонг":"ssangyong",
"genesis":"genesis","дженезіс":"genesis",

"geely":"geely","джилі":"geely",
"chery":"chery","чері":"chery",
"haval":"haval","хавал":"haval",
"great wall":"great wall","грейт вол":"great wall",
"byd":"byd",
"baic":"baic",
"jac":"jac",
"dongfeng":"dongfeng","донгфенг":"dongfeng",
"changan":"changan","чанган":"changan",
"faw":"faw",
"lifan":"lifan","ліфан":"lifan",
"xpeng":"xpeng",
"nio":"nio",
"zeekr":"zeekr",
"gac":"gac",
"jetour":"jetour",
"ora":"ora",
"lynk & co":"lynk & co",
"hongqi":"hongqi",

"man":"man","ман":"man",
"scania":"scania","сканія":"scania",
"volvo":"volvo","вольво":"volvo",
"daf":"daf",
"iveco":"iveco","івеко":"iveco",
"freightliner":"freightliner",
"mack":"mack",
"peterbilt":"peterbilt",
"kenworth":"kenworth",

"bogdan":"bogdan","богдан":"bogdan",
"etalon":"etalon","еталон":"etalon",
"laz":"laz","лаз":"laz",
"ikarus":"ikarus","ікарус":"ikarus",
"neoplan":"neoplan",
"setra":"setra",
"yutong":"yutong",
"king long":"king long",

"lada":"lada","лада":"lada",
"vaz":"vaz","ваз":"vaz",
"gaz":"gaz","газ":"gaz",
"uaz":"uaz","уаз":"uaz",
"maz":"maz","маз":"maz",
"kamaz":"kamaz","камаз":"kamaz",
"zaz":"zaz","заз":"zaz"
}
GENERIC_VEHICLE_WORDS = {
    "машина", "машинка", "авто", "автомобиль", "тачка", "транспорт",
    "легковая", "легковой", "грузовая", "грузовик", "бус",
    "мікроавтобус", "автобус", "джип", "кроссовер"
}